sonar.projectKey=marekmaciejewski_scholka-aureolka-website
sonar.organization=marekmaciejewski
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=src,public,index.html,gallery,schedule,contact,vite.config.ts,eslint.config.js,tsconfig.json,tsconfig.app.json,tsconfig.node.json
sonar.exclusions=dist/**,node_modules/**,public/*.png,public/**/*.png,public/*.jpg,public/**/*.jpg,public/*.jpeg,public/**/*.jpeg,public/*.webp,public/**/*.webp,public/*.ico,public/**/*.ico,public/*.gif,public/**/*.gif,public/*.avif,public/**/*.avif
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts,tests/**/*.tsx
sonar.coverage.exclusions=src/main.tsx,vite.config.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
